services:
  supla-plex-webhook:
    build:
      context: /home/user/appdata/supla-plex-webhook/
      dockerfile: supla-plex-webhook
    container_name: supla-plex-webhook
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "3000:3000"
    volumes:
      - /home/user/appdata/supla-plex-webhook/data:/data
    restart: unless-stopped